[package]
name = "TEST_VIA_RUSTUP_WASM_WASI_TARGET"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
